<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IncludeBuildOutput>false</IncludeBuildOutput>

		<PackageId>Reprimand.Mmhook</PackageId>
		<Version>0.1.0-beta.3</Version>
		<Authors>belshftl</Authors>
		<Description>extra HookGen events for Celeste mods from the Reprimand project</Description>
		<Copyright>Copyright (c) 2026 belshftl</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/belshftl/Reprimand</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Include="MMHOOK_Celeste.RmExtras.dll" Pack="true" PackagePath="lib/net8.0/" />
		<None Include="../README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
