<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IncludeBuildOutput>false</IncludeBuildOutput>

		<PackageId>Reprimand.Mmhook</PackageId>
		<Version>0.1.0-beta.1</Version>
		<Authors>belshftl</Authors>
		<Description>extra HookGen events for Celeste mods from the Reprimand project</Description>
		<Copyright>Copyright (c) 2026 belshftl</Copyright>
		<!-- nuget only supports spdx v2, TODO figure something out -->
		<!-- <PackageLicenseExpression>LGPL-3.0-only WITH AdditionRef-LGPLv3-Celeste-Target-Platform-Exception</PackageLicenseExpression> -->
		<RepositoryUrl>https://github.com/belshftl/Reprimand</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Include="MMHOOK_Celeste.RmExtras.dll" Pack="true" PackagePath="lib/net8.0/" />
	</ItemGroup>
</Project>
