<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<PackageId>Reprimand</PackageId>
		<Version>0.1.0-beta.6</Version>
		<Authors>belshftl</Authors>
		<Description>a utility library for Celeste mods (the portion that doesn't require a runtime dependency mod)</Description>
		<Copyright>Copyright (c) 2026 belshftl</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/belshftl/Reprimand</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<CelestePrefix Condition="'$(CelestePrefix)' == '' And Exists('../../../Celeste.dll')">../../..</CelestePrefix>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Reprimand.Runtime" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.4" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<!-- intentionally do not pull CelesteAnalyzer -->
		<PackageReference Include="CelesteMod.Publicizer" Version="1.1.2" CelesteAssembly="$(CelestePrefix)/Celeste.dll" />
		<Reference Include="$(CelestePrefix)/FNA.dll" Private="false" />
		<Reference Include="$(CelestePrefix)/MMHOOK_Celeste.dll" Private="false" />
	</ItemGroup>

	<ItemGroup>
		<None Include="buildTransitive/$(PackageId).targets" Pack="true" PackagePath="buildTransitive/$(PackageId).targets" />
		<None Include="../README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
