// SPDX-FileCopyrightText: 2026 belshftl
// SPDX-License-Identifier: MIT

using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Reprimand.Analyzers.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class LogWrapperGenerator : IIncrementalGenerator {
	private const string attributeNamespace = "Reprimand.Generated";
	private const string attributeTypeName = "LogWrapperAttribute";
	private const string defaultAlias = "Log";

	private const string wrapperNamespace = "Reprimand.Generated";
	private const string wrapperTypeName = "__Reprimand_LogWrapper";

	private const string attributeSource =
@"// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

namespace Reprimand.Generated {
	/// <summary>
	/// Enables generation of a <see cref=""global::Celeste.Mod.Logger""/> logging wrapper for this
	/// assembly and configures its log tag and global using alias.
	/// </summary>
	/// <remarks>
	/// If this attribute is not applied, no logging wrapper is generated.
	/// </remarks>
	[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
	internal sealed class LogWrapperAttribute : global::System.Attribute {
		/// <summary>
		/// Initializes the logging generator configuration.
		/// </summary>
		/// <param name=""tag"">
		/// The tag passed to each generated logger call.
		/// </param>
		public LogWrapperAttribute(string tag) {
			Tag = tag;
		}

		/// <summary>
		/// The tag passed to each generated logger call.
		/// </summary>
		public string Tag { get; }

		/// <summary>
		/// The name of the generated global using alias. Defaults to <c>Log</c>.
		/// </summary>
		public string Alias { get; init; } = ""Log"";
	}
}
";

	private enum ConfigurationState {
		Missing,
		Valid,
		InvalidTag,
		InvalidAlias
	}

	private readonly struct Configuration : IEquatable<Configuration> {
		private Configuration(ConfigurationState state, string? tag, string? alias) {
			State = state;
			Tag = tag;
			Alias = alias;
		}

		public ConfigurationState State { get; }
		public string? Tag { get; }
		public string? Alias { get; }

		public static Configuration Valid(string tag, string alias) => new(ConfigurationState.Valid, tag, alias);
		public static Configuration InvalidTag() => new(ConfigurationState.InvalidTag, null, null);
		public static Configuration InvalidAlias(string? alias) => new(ConfigurationState.InvalidAlias, null, alias);

		public bool Equals(Configuration other) => State == other.State && Tag == other.Tag && Alias == other.Alias;
		public override bool Equals([NotNullWhen(true)] object? obj) => obj is Configuration other && Equals(other);
		public override int GetHashCode() {
			// HashCode.Combine is not in this .net version
			unchecked {
				int h = (int)State;
				if (Tag is not null)
					h = (h * 397) ^ StringComparer.Ordinal.GetHashCode(Tag);
				if (Alias is not null)
					h = (h * 397) ^ StringComparer.Ordinal.GetHashCode(Alias);
				return h;
			}
		}
	}

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		context.RegisterPostInitializationOutput(static ctx => {
			ctx.AddEmbeddedAttributeDefinition();
			ctx.AddSource("LogWrapperAttribute.g.cs", SourceText.From(attributeSource, Encoding.UTF8));
		});

		IncrementalValueProvider<Configuration> cfg = context.CompilationProvider.Select(
			static (comp, _) => {
				foreach (AttributeData attr in comp.Assembly.GetAttributes()) {
					INamedTypeSymbol? attrClass = attr.AttributeClass;
					if (
						attrClass is null || attrClass.Name != attributeTypeName || attrClass.ContainingType is not null ||
						attrClass.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) != "global::" + attributeNamespace
					)
						continue;
					if (attr.ConstructorArguments.Length != 1 || attr.ConstructorArguments[0].Value is not string tag)
						return Configuration.InvalidTag();
					string alias = defaultAlias;
					foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments) {
						if (named.Key != "Alias")
							continue;
						if (named.Value.Value is not string configuredAlias)
							return Configuration.InvalidAlias(null);
						alias = configuredAlias;
						break;
					}
					if (!SyntaxFacts.IsValidIdentifier(alias))
						return Configuration.InvalidAlias(alias);
					return Configuration.Valid(tag, alias);
				}
				return default;
			});

		context.RegisterSourceOutput(
			cfg,
			static (ctx, cfg) => {
				if (cfg.State == ConfigurationState.Missing)
					return;
				if (cfg.State == ConfigurationState.InvalidTag) {
					ctx.ReportDiagnostic(Diagnostic.Create(Diagnostics.Generators.InvalidLogTag, Location.None));
					return;
				}
				if (cfg.State == ConfigurationState.InvalidAlias) {
					ctx.ReportDiagnostic(Diagnostic.Create(Diagnostics.Generators.InvalidLogAlias, Location.None, cfg.Alias ?? "<null>"));
					return;
				}

				string tagLiteral = SymbolDisplay.FormatLiteral(cfg.Tag!, quote: true);
				StringBuilder sb = new(2048);

				sb.AppendLine("// <auto-generated/>");
				sb.AppendLine("#nullable enable");
				sb.AppendLine("#pragma warning disable CS1591");

				sb.Append("global using ").Append(cfg.Alias).Append(" = global::").Append(wrapperNamespace).Append('.').Append(wrapperTypeName).AppendLine(";");
				sb.Append("namespace ").Append(wrapperNamespace).AppendLine(";");
				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Provides convenience wrapper methods for <see cref=\"global::Celeste.Mod.Logger\"/> that automatically");
				sb.AppendLine("/// attach the configured tag to every message.");
				sb.AppendLine("/// </summary>");
				sb.Append("internal static class ").Append(wrapperTypeName).AppendLine(" {");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// The tag attached to each message.");
				sb.AppendLine("/// </summary>");
				sb.Append("\tpublic const string Tag = ").Append(tagLiteral).AppendLine(";");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Logs a message with the specified severity level.");
				sb.AppendLine("/// </summary>");
				sb.AppendLine("\tpublic static void Report(global::Celeste.Mod.LogLevel lvl, string msg) => global::Celeste.Mod.Logger.Log(lvl, Tag, msg);");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Logs a message with <see cref=\"global::Celeste.Mod.LogLevel.Verbose\"/> severity level.");
				sb.AppendLine("/// </summary>");
				sb.AppendLine("\tpublic static void Verbose(string msg) => global::Celeste.Mod.Logger.Log(global::Celeste.Mod.LogLevel.Verbose, Tag, msg);");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Logs a message with <see cref=\"global::Celeste.Mod.LogLevel.Debug\"/> severity level.");
				sb.AppendLine("/// </summary>");
				sb.AppendLine("\tpublic static void Debug(string msg) => global::Celeste.Mod.Logger.Log(global::Celeste.Mod.LogLevel.Debug, Tag, msg);");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Logs a message with <see cref=\"global::Celeste.Mod.LogLevel.Info\"/> severity level.");
				sb.AppendLine("/// </summary>");
				sb.AppendLine("\tpublic static void Info(string msg) => global::Celeste.Mod.Logger.Log(global::Celeste.Mod.LogLevel.Info, Tag, msg);");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Logs a message with <see cref=\"global::Celeste.Mod.LogLevel.Warn\"/> severity level.");
				sb.AppendLine("/// </summary>");
				sb.AppendLine("\tpublic static void Warn(string msg) => global::Celeste.Mod.Logger.Log(global::Celeste.Mod.LogLevel.Warn, Tag, msg);");

				sb.AppendLine("/// <summary>");
				sb.AppendLine("/// Logs a message with <see cref=\"global::Celeste.Mod.LogLevel.Error\"/> severity level.");
				sb.AppendLine("/// </summary>");
				sb.AppendLine("\tpublic static void Error(string msg) => global::Celeste.Mod.Logger.Log(global::Celeste.Mod.LogLevel.Error, Tag, msg);");

				sb.AppendLine("}");

				ctx.AddSource("LogWrapper.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
			});
	}
}
